dist: bionic
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0
before_install:
  - gimme 1.14.1
  - source ~/.gimme/envs/go1.14.1.env
  - curl -s https://releases.hashicorp.com/consul/1.7.2/consul_1.7.2_linux_amd64.zip >/tmp/consul.zip; sudo unzip -d /usr/local/bin /tmp/consul.zip; sudo chmod 755 /usr/local/bin/consul
  - "consul agent -dev -node machine >/tmp/consul.log 2>&1 &"
script: "make && make test && (bundle exec rake || (tail -n 50 tmp/*.{log,output}; false))"
services:
  - redis-server
  - rabbitmq
  - mysql
addons:
  apt:
    sources:
      - sourceline: "deb https://packages.erlang-solutions.com/ubuntu bionic contrib"
        key_url: "https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc"
      - sourceline: "deb https://dl.bintray.com/rabbitmq/debian bionic main"
        key_url: "https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc"
    packages:
      - rabbitmq-server
