dist: bionic
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
before_install:
  - gimme 1.14.1
  - source ~/.gimme/envs/go1.14.1.env
  - curl -s https://releases.hashicorp.com/consul/1.7.2/consul_1.7.2_linux_amd64.zip >/tmp/consul.zip; sudo unzip -d /usr/local/bin /tmp/consul.zip; sudo chmod 755 /usr/local/bin/consul
  - "consul agent -dev -node machine >/tmp/consul.log 2>&1 &"
script: "make && make test && (bundle exec rake || (tail -n 50 tmp/*.{log,output}; false))"
services:
  - redis-server
  - rabbitmq
  - mysql
addons:
  apt:
    packages:
      - rabbitmq-server
