rvm:
  - 2.3.5
  - 2.4.2
before_script:
  - sudo rm -rf /usr/local/go
  - curl -s https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz | sudo tar xzCf /usr/local -
  - export GOROOT=/usr/local/go
  - export PATH=/usr/local/go/bin:$PATH
  - sudo lsof -Pn | grep TCP
script: "make && bundle exec rake || tail -n +1 tmp/*output"
services:
  - redis-server
  - rabbitmq
sudo: required
